version: "3.8"
services:
  db:
    image: postgres:16
    container_name: expense_trackerDB
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: split_house
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d split_house"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
